server:
  port: 9090

spring:
  application:
    name: notifications
  server:
    port: 0
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/notifications?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    listener:
      simple:
        retry:
          enabled: true
          multiplier: 3.0
          initial-interval: 5000
          max-attempts: 10
          max-interval: 30000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000
      refresh-token:
        expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html

rabbitmq:
  queue:
    name: notifications

jwt:
  token: Re$tToken

# https://github.com/ali-bouali/spring-boot-3-jwt-security